services:
  - type: web
    name: nexus-backend
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: singapore # or oregon / frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
