# ================================
# Nexus Backend - App Configuration
# ================================

server.port=8080

# PostgreSQL - Supabase (transaction pooler port 6543)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.khvitvsltqxyurrsvdtl
spring.datasource.password=ruchitajadhav27
spring.datasource.driver-class-name=org.postgresql.Driver

## HikariCP - limit pool size for Supabase free tier
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=2

# HikariCP - limit connections for Supabase free tier
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
nexus.jwt.secret=NexusCorpTrainingCenterSecretKey2026SuperSecureKey
nexus.jwt.expiration-ms=86400000

# SMTP - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jadhavruchita27@gmail.com
spring.mail.password=bzdfkfuvqvpgsbnm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# Enquiry notification recipient
nexus.enquiry.admin-email=jadhavruchita27@gmail.com


# CORS
nexus.cors.allowed-origins=http://localhost:8081,http://localhost:19006,exp://localhost:8081,http://10.0.2.2:8081,http://10.0.2.2:19006

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB