# ================================
# Nexus Backend - App Configuration
# ================================

server.port=8080

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.khvitvsltqxyurrsvdtl
spring.datasource.password=ruchitajadhav27
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
nexus.jwt.secret=NexusCorpTrainingCenterSecretKey2026SuperSecureKey
nexus.jwt.expiration-ms=86400000

# SMTP - Gmail (replace with your Gmail + App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jadhavruchita27@gmail.com
spring.mail.password=bzdfkfuvqvpgsbnm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# CORS
nexus.cors.allowed-origins=http://localhost:8081,http://localhost:19006,exp://localhost:8081
